tubemap = {
#green line
"Pasir ris" : {"Tampines":2},
"Tampines": {"Simei":2, "Pasir ris":2,"75009:72":2},
"Simei": {"Taneh Merah":2, "Tampines":2},
"Taneh Merah":{"Simei":2, "Changi Airport":2,"Bedok":2},
"Bedok":{"Kembangan":2,"Taneh Merah":2},
"Kembangan":{"Eunos":2, "Bedok":2},
"Eunos":{"Paya Lebar":2, "Kembangan":2},
"Paya Lebar":{"Aljunied":2, "Eunos":2},
"Aljunied":{"Kallang":2, "Paya Lebar":2},
"Kallang":{"Lavender":2, "Aljunied":2},
"Lavender":{"Bugis":2, "Kallang":2},
"Bugis":{"City Hall":2, "Lavender":2},
"City Hall":{"Raffles Place":2, "Bugis":2,"Dhoby Ghaut":2},
"Raffles Place":{"Tanjong Pagar":2, "City Hall":2, "Marina Bay":2},
"Tanjong Pagar":{"Outram Park":2, "Raffles Place":2},
"Outram Park":{"Tiong Bahru":2, "Tanjong Pagar":2},
"Tiong Bahru":{"Redhill":2, "Outram Park":2},
"Redhill": {"Queenstown":2, "Tiong Bahru":2},
"Queenstown": {"Commonwealth":2, "Redhill":2},
"Commonwealth":{"Buona Vista":2, "Queenstown":2},
"Buona Vista":{"Dover":2,"Commonwealth":2},
"Dover":{"Clementi":2, "Buona Vista":2},
"Clementi":{"Jurong East":2, "Dover":2},
"Jurong East":{"Chinese Garden":2, "Clementi":2,"Bukit Batok":2},
"Chinese Garden":{"Lakeside":2, "Jurong East":2},
"Lakeside":{"Boon Lay":2, "Chinese Garden":2},
"Boon Lay":{"Pioneer":2, "Lakeside":2},
"Pioneer":{"Joo Koon":2, "Boon Lay":2},
"Joo Koon":{"Pioneer":2},

#red line
"Marina South Pier":{"Marina Bay":2,},
"Marina Bay":{"Raffles Place":2, "Marina South Pier":2},
"Dhoby Ghaut":{"City Hall":2, "Somerset":2},
"Somerset":{"Orchard":2, "Dhoby Ghaut":2},
"Orchard":{"Newton":2, "Somerset":2},
"Newton":{"Novena":2, "Orchard":2},
"Novena":{"Toa Payoh":2, "Newton":2},
"Toa Payoh":{"Braddell":2, "Novena":2},
"Braddell":{"Bishan":2, "Toa Payoh":2},
"Bishan":{"Ang Mo Kio":2, "Braddell":2},
"Ang Mo Kio":{"Yio Chu Kang":2, "Bishan":2},
"Yio Chu Kang":{"Khatib":2, "Ang Mo Kio":2,"55509:72":2},
"Khatib":{"Yishun":2, "Yio Chu Kang":2},
"Yishun":{"Canberra":2, "Khatib":2},
"Canberra":{"Sembawang":2, "Yishun":2},
"Sembawang":{"Admiralty":2, "Canberra":2},
"Admiralty":{"Woodlands":2, "Sembawang":2},
"Woodlands":{"Marsiling":2, "Admiralty":2},
"Marsiling":{"Kranji":2, "Woodlands":2},
"Kranji":{"Sungei Kadut":2, "Marsiling":2},
"Sungei Kadut":{"Yew Tee":2, "Kranji":2},
"Yew Tee":{"Choa Chu Kang":2, "Sungei Kadut":2},
"Choa Chu Kang":{"Bukit Gombak":2, "Yew Tee":2},
"Bukit Gombak":{"Bukit Batok":2, "Choa Chu Kang":2},
"Bukit Batok":{"Jurong East":2, "Bukit Gombak":2},

#Bus 72
"55509:72":{"Yio Chu Kang":2,"75009:72":5},
"75009:72":{"Tampines":2,"55509:72":5},

}
